<?php

namespace Database\Seeders;

use App\Models\Employee;
use App\Models\Office;
use Illuminate\Database\Seeder;

class EmployeeSeeder extends Seeder
{
    public function run(): void
    {
        $validOfficeIds = Office::query()->pluck('id')->map(fn ($id) => (int) $id)->all();

        foreach ($this->employees() as $employee) {
            $officeId = in_array((int) $employee['office_id'], $validOfficeIds, true)
                ? (int) $employee['office_id']
                : null;

            Employee::updateOrCreate(
                ['ee_sequence_number' => $employee['ee_sequence_number']],
                [
                    'first_name' => $employee['first_name'],
                    'middle_name' => $employee['middle_name'],
                    'last_name' => $employee['last_name'],
                    'office_id' => $officeId,
                    'position' => $employee['position'],
                    'status' => true,
                ]
            );
        }
    }

    /**
     * @return list<array{ee_sequence_number: string, first_name: string, middle_name: ?string, last_name: string, office_id: int, position: ?string}>
     */
    protected function employees(): array
    {
        $rows = [
            ['A', 'c/o', null, 'Auditor', 31, null],
            ['B', 'c/o', null, 'Baguio', 31, null],
            ['C', 'c/o', null, 'Ifugao PO', 31, null],
            ['D1', 'C/O', null, 'of supply', 29, null],
            ['E1', 'c/o', null, 'RHO', 31, null],
            ['E2', 'c/o', null, 'TMSD', 31, null],
            ['D2', 'for', null, 'issuance', 31, null],
            ['E3', 'for', null, 'issuance (reissuance)', 31, null],
            ['D3', 'no', null, 'ics', 31, null],
            ['E4', 'Supply', null, 'Supply', 29, null],
            ['1', 'William', 'T.', 'Abay', 25, 'Tribal Affairs Assistant II - 08'],
            ['2', 'Mevelyn', 'F.', 'Adchak', 17, 'Midwife II - 11'],
            ['3', 'Atanacio', 'D.', 'Addog', 30, 'Director IV - 28'],
            ['4', 'Belha', 'C.', 'Afidchao', 17, 'Administrative Aide I - 01'],
            ['5', 'Alexander Jr.', 'G.', 'Aguana', 17, 'Nurse II - 16'],
            ['6', 'Divina', 'P.', 'Agunos', 1, 'Administrative Aide IV - 04'],
            ['7', 'Leo', null, 'Agustin', 31, null],
            ['8', 'Carlito', 'Y.', 'Aiso', 15, 'Engineer II - 16'],
            ['9', 'Allan', 'W.', 'Allatis', 9, 'Community Dev\'t Officer III - 18'],
            ['10', 'Bruno Jr.', 'H.', 'Almora', 32, 'Engineer II - 16'],
            ['11', 'Louie', 'P.', 'Ananayo', 21, 'Nurse II - 16'],
            ['12', 'Arwin', 'P.', 'Angway', 10, 'Nurse II - 16'],
            ['13', 'Andrelyn', 'S.', 'Antonio', 9, 'Administrative Aide I - 01'],
            ['14', 'Catherine', 'G.', 'Apaling', 22, 'Dev\'t Mgmt Officer V - 24'],
            ['15', 'Randolf', 'S.', 'Aridao', 1, 'Administrative Aide I - 01'],
            ['16', 'Genalyn', 'B.', 'As-il', 10, 'Community Affairs Officer I - 11'],
            ['17', 'Raizel', 'N.', 'Ateo-an', 14, 'Administrative Aide IV - 04'],
            ['18', 'Ricky Neil Carter', 'B.', 'Ayabo', 3, 'Tribal Affairs Assistant I - 05'],
            ['19', 'Archie', 'A.', 'Baccoy', 25, 'Community Affairs Officer I - 11'],
            ['20', 'Gloria', 'R.', 'Badua', 10, 'Midwife II - 11'],
            ['21', 'Brigette', 'B.', 'Baggas', 24, 'Midwife II - 11'],
            ['22', 'Heny', 'B.', 'Bahiwag', 18, 'Administrative Aide IV - 04'],
            ['23', 'Maria Ricanica', 'P.', 'Balaoag', 5, 'Tribal Affairs Assistant II - 08'],
            ['24', 'Aurora', 'T.', 'Balong', 9, 'Tribal Affairs Assistant II - 08'],
            ['25', 'Warren', 'L.', 'Bandoc', 15, 'Tribal Affairs Assistant II - 08'],
            ['26', 'Lyman Benito', 'W.', 'Bangao', 32, 'Engineer III - 19'],
            ['27', 'Glenden', 'A.', 'Barbarona', 6, 'Tribal Affairs Assistant I - 05'],
            ['28', 'Renato', 'B.', 'Basa', 5, 'Administrative Aide III - 03'],
            ['29', 'Dennis', 'N.', 'Basal', 29, 'Administrative Officer III - 14'],
            ['30', 'Grace', 'C.', 'Batanes', 33, 'Community Affairs Officer I - 11'],
            ['31', 'Remelyn', 'K.', 'Bayani', 1, 'Tribal Affairs Assistant II - 08'],
            ['32', 'Joy', 'B.', 'Bayongasan', 15, 'Nurse II - 16'],
            ['33', 'Sheryl Marie', 'A.', 'Belagan', 32, 'Community Affairs Officer I - 11'],
            ['34', 'Jayson', 'M.', 'Belisario', 7, 'Community Development Officer III'],
            ['35', 'Norman', 'C.', 'Bernardez', 8, 'Nurse II - 16'],
            ['36', 'Minnie Grace', 'G.', 'Beyon', 2, 'Administrative Aide I - 01'],
            ['37', 'Avelina', 'L.', 'Bimmuyag', 20, 'Tribal Affairs Assistant II - 08'],
            ['38', 'Shezel', 'A.', 'Biscarra', 6, 'Community Affairs Officer I - 11'],
            ['39', 'Angelita', 'L.', 'Biscarra', 7, 'Tribal Affairs Assistant I - 05'],
            ['40', 'Austin', 'D.', 'Bisin', 1, 'Administrative Aide III - 03'],
            ['41', 'Kristan', 'G.', 'Bitao', 24, 'Administrative Aide I - 01'],
            ['42', 'Rodel Sr.', 'D.', 'Bongay', 3, 'Administrative Aide I - 01'],
            ['43', 'Cynthia', 'B.', 'Budaden', 5, 'Attorney IV - 23'],
            ['44', 'Jared', 'B.', 'Bullayao', 25, 'Tribal Affairs Assistant I - 05'],
            ['45', 'Victor', 'P.', 'Bumatnong', 32, 'Engineer II - 16'],
            ['46', 'Welmer', 'B.', 'Bumosao', 22, 'Administrative Officer IV - 15'],
            ['47', 'Paulina', 'S.', 'Bungubong', 12, 'Midwife II - 11'],
            ['48', 'Grazeil Joy', 'C.', 'Butgui', 30, 'Community Affairs Officer II - 15'],
            ['49', 'Virgilio', 'V.', 'Cabanas', 6, 'Administrative Aide I - 01'],
            ['50', 'Sharon', 'L.', 'Cabato', 33, 'Administrative Officer IV - 15'],
            ['51', 'Marilou', 'C.', 'Cabinta', 32, 'Medical Officer III - 21'],
            ['52', 'Judith', 'T.', 'Cadias', 33, 'Community Dev\'t Officer III - 18'],
            ['53', 'Geoffry', 'A.', 'Calderon', 22, 'Attorney IV - 23'],
            ['54', 'Sheryl', 'G.', 'Calsiyao', 24, 'Nurse II - 16'],
            ['55', 'Racquel', 'Q.', 'Calubing', 6, 'Midwife II - 11'],
            ['56', 'Bernardo', 'G.', 'Canao', 25, 'Community Development Officer III'],
            ['57', 'Jeckerson', 'T.', 'Cariño', 10, 'Administrative Aide I - 01'],
            ['58', 'Gliceria', 'A.', 'Catores', 9, 'Administrative Aide IV - 04'],
            ['59', 'Siegfred', 'B.', 'Chanfing', 9, 'Tribal Affairs Assistant II - 08'],
            ['60', 'Nora', 'T.', 'Chulipa', 29, 'Chief Admin. Officer - 24'],
            ['61', 'Abilene', 'A.', 'Cirilo', 30, 'Community Dev\'t Officer III - 18'],
            ['62', 'Maritess', 'S.', 'C30ero', 33, 'Administrative Aide I - 01'],
            ['63', 'Johnpen', 'T.', 'Dalos', 12, 'Community Affairs Officer I - 11'],
            ['64', 'Jonifer Mae', 'C.', 'Damag', 19, 'Nurse II - 16'],
            ['65', 'Jamie Grace', 'D.', 'Damian', 23, 'Nurse II - 16'],
            ['66', 'Joyner', 'L.', 'Dammay', 2, 'Community Dev\'t Officer III - 18'],
            ['67', 'Cristina Desiree', 'G.', 'Damullan', 8, 'Tribal Affairs Assistant II - 08'],
            ['68', 'Jezryl', 'I.', 'De Peralta', 3, 'Community Dev\'t Officer III - 18'],
            ['69', 'Fritzie', 'D.', 'Depdepen', 4, 'Tribal Affairs Assistant I - 05'],
            ['70', 'Rachelle', 'G.', 'Dereje', 33, 'Nurse II - 16'],
            ['71', 'Claver', 'B.', 'Dinanas', 24, 'Community Affairs Officer I - 11'],
            ['72', 'Editha', 'T.', 'Dinayugan', 2, 'Community Affairs Officer I - 11'],
            ['73', 'Cynthia', 'L.', 'Dogwe', 18, 'Attorney IV - 23'],
            ['74', 'Ethel Jeneleah', 'M.', 'Dongdongan', 25, 'Nurse II - 16'],
            ['75', 'Bryan Christopher', 'C.', 'Donggayao', 30, 'Attorney IV - 23'],
            ['76', 'Gary', 'P.', 'Dong-gayao', 33, 'Tribal Affairs Assistant II - 08'],
            ['77', 'Jocelyn', 'P.', 'Dula', 16, 'Tribal Affairs Assistant I - 05'],
            ['78', 'Vilma', 'G.', 'Dumbab', 23, 'Community Affairs Officer I - 11'],
            ['79', 'Noemi', 'F.', 'Duran', 3, 'Community Affairs Officer I - 11'],
            ['80', 'Vilma', 'L.', 'Epi', 29, 'Administrative Assistant II - 08'],
            ['81', 'Graces Cleofas', 'B.', 'Escala', 6, 'Nurse II - 16'],
            ['82', 'Genaro', 'A.', 'Failoga', 4, 'Community Dev\'t Officer III - 18'],
            ['83', 'Juan', 'B.', 'Falinchao', 17, 'Community Dev\'t Officer III - 18'],
            ['84', 'Patricia', 'D.', 'Fianza', 13, 'Nurse I - 15'],
            ['85', 'April Mae', 'C.', 'Foy-os', 32, 'Administrative Aide I V- 04'],
            ['86', 'Lily May', 'T.', 'Francisco', 11, 'Community Dev\'t Officer III - 18'],
            ['87', 'Agnes', 'D.', 'Gabuat', 1, 'Dev\'t Mgmt Officer V - 24'],
            ['88', 'Edwin', 'N.', 'Galajya', 20, 'Administrative Aide I - 01'],
            ['89', 'Alderbert', 'R.', 'Galera', 5, 'Engineer II - 16'],
            ['90', 'Reagan', 'S.', 'Galunza', 11, 'Tribal Affairs Assistant II - 08'],
            ['91', 'Marjorie', 'M.', 'Galut', 4, 'Nurse II - 16'],
            ['92', 'Joselyn', 'T.', 'Gamongan', 13, 'Tribal Affairs Assistant II - 08'],
            ['93', 'Mailyn', 'S.', 'Garcia', 33, 'Tribal Affairs Assistant II - 08'],
            ['94', 'Sylvia', 'D.', 'Gawon', 22, 'Administrative Aide IV - 04'],
            ['95', 'Kareen', 'B.', 'Gayudan', 28, '28'],
            ['96', 'Cherry', 'D.', 'Ginpac', 16, 'Tribal Affairs Assistant II - 08'],
            ['97', 'Santos', 'W.', 'Godio', 13, 'Community Affairs Officer I - 11'],
            ['98', 'Christian Hilton', 'L.', 'Gorio', 29, 'Administrative Aide IV - 04'],
            ['99', 'Maribel', 'Z.', 'Gorospe', 4, 'Midwife II - 11'],
            ['100', 'Herminio', 'B.', 'Gumawang', 22, 'Tribal Affairs Assistant II - 08'],
            ['101', 'Norina', 'D.', 'Habiatan', 21, 'Community Dev\'t Officer III - 18'],
            ['102', 'Ben Jr.', 'L.', 'Hidalgo', 21, 'Tribal Affairs Assistant I - 05'],
            ['103', 'Aida', 'P.', 'Higino', 15, 'Tribal Affairs Assistant I - 05'],
            ['104', 'Arjay', 'C.', 'Idao', 7, 'Tribal Affairs Assistant II - 08'],
            ['105', 'Mazshaerra', 'A.', 'Idao', 5, 'Tribal Affairs Assistant I - 05'],
            ['106', 'Jezryl', 'I.', 'De Peralta', 3, null],
            ['107', 'Jocelyn', 'L.', 'Jose', 12, 'Nurse II - 16'],
            ['108', 'Marcos', 'L.', 'Jose', 12, 'Community Dev\'t Officer III - 18'],
            ['109', 'Melina', 'P.', 'Jose', 9, 'Community Affairs Officer I - 11'],
            ['110', 'Myra', 'A.', 'Kalang-ad', 33, 'Attorney IV - 23'],
            ['111', 'Wilson', 'K.', 'Kalangeg', 14, 'Dev\'t Mgmt Officer V - 24'],
            ['112', 'Grace', 'F.', 'Keworna', 16, 'Community Affairs Officer I - 11'],
            ['113', 'Jan Yuri', 'D.', 'Kinggingan', 19, 'Community Affairs Officer I - 11'],
            ['114', 'Lloyd Neil', 'C.', 'La Madrid', 29, 'Administrative Officer III - 14'],
            ['115', 'Marissa', 'L.', 'Bas-Ilan', 31, 'Administrative Aide VI - 06'],
            ['116', 'Carlo', 'D.', 'Labuguen', 6, 'Tribal Affairs Assistant II - 08'],
            ['117', 'Regina', 'E.', 'Ladip', 29, 'Administrative Officer V - 18'],
            ['118', 'Precy Jane', 'F.', 'Lamangen', 14, 'Tribal Affairs Assistant I - 05'],
            ['119', 'Greisham', 'S.', 'Lamsis', 9, 'Administrative Aide III - 03'],
            ['120', 'Raquel', 'L.', 'Lardizabal', 29, 'Administrative Officer V - 18'],
            ['121', 'Mariano', 'N.', 'Lawad', 24, 'Tribal Affairs Assistant II - 08'],
            ['122', 'Esther', 'N.', 'Licnachan', 18, 'Dev\'t Mgmt Officer V - 24'],
            ['123', 'Milagros', 'K.', 'Limangan', 19, 'Midwife II - 11'],
            ['124', 'Rogelio Jr.', 'V.', 'Lokino', 11, 'Administrative Aide I - 01'],
            ['125', 'Andrew James', 'N.', 'Lomioan', 5, 'Administrative Aide I - 01'],
            ['126', 'Jason', 'F.', 'Lubang', 14, 'Administrative Aide I - 01'],
            ['127', 'Gerry', 'H.', 'Lumawig', 18, 'Tribal Affairs Assistant I - 05'],
            ['128', 'Jasmin Gamay', 'D.', 'Lumiqued', 29, 'Accountant III - 19'],
            ['129', 'Severino Manuel', 'G.', 'Lumiqued', 9, 'Attorney IV - 23'],
            ['130', 'Esperanza', 'L.', 'Lupante', 32, 'Planning Officer II - 15'],
            ['131', 'Anneleis Marie', 'D.', 'Mabazza', 22, 'Community Dev\'t Officer III - 18'],
            ['132', 'Ronalvin', 'F.', 'Mabli', 9, 'Engineer 1 - 12'],
            ['133', 'Norea', 'T.', 'Madchiw', 20, 'Nurse II - 16'],
            ['134', 'Daisy Ann', 'B.', 'Maga-ao', 22, 'Tribal Affairs Assistant I - 05'],
            ['135', 'Ana Marie', 'K.', 'Magwa', 16, 'Community Dev\'t Officer III - 18'],
            ['136', 'Rosa', 'H.', 'Malana', 21, 'Administrative Aide I - 01'],
            ['137', 'Karla Dazzale Marie', 'T.', 'Mallillin', 1, 'Tribal Affairs Assistant I - 05'],
            ['138', 'Milagrail', 'B.', 'Mamauag', 2, 'Nurse II - 16'],
            ['139', 'Merly', 'P.', 'Manganip', 4, 'Tribal Affairs Assistant II - 08'],
            ['140', 'Mayla', 'P.', 'Martin', 21, 'Midwife II - 11'],
            ['141', 'Triffany Prudence', 'S.', 'Martin', 7, 'Nurse II - 16'],
            ['142', 'Brain', 'S.', 'Masweng', 31, 'Attorney VI - 26'],
            ['143', 'Bertrand', 'J.', 'Melad', 2, null],
            ['144', 'Raym', 'rt', 'Miguingan', 8, 'Administrative Aide I - 01'],
            ['145', 'Urbano', 'B.', 'Mirante', 33, 'Dev\'t Mgmt Officer V - 24'],
            ['146', 'Katherine', 'W.', 'Molina', 23, 'Administrative Aide I - 01'],
            ['147', 'Raizel', 'T.', 'Napaeg', 14, null],
            ['148', 'Rocky Jake', 'C.', 'Ngalob', 9, 'Administrative Officer IV - 15'],
            ['149', 'Roger', 'B.', 'Ngao-i', 23, 'Community Dev\'t Officer III - 18'],
            ['150', 'Carla', 'M.', 'Ngayaan', 25, 'Midwife II - 11'],
            ['151', 'Florena', 'C.', 'Ngiyos', 9, 'TAA I'],
            ['152', 'Denver', 'L.', 'Nobleza', 14, 'Tribal Affairs Assistant II - 08'],
            ['153', 'Jaime', 'D.', 'Ognayon', 18, 'Administrative Aide III - 03'],
            ['154', 'Janine Teen', 'I.', 'Pacalso', 30, 'Midwife II - 11'],
            ['155', 'Cliff30', 'K.', 'Padonga', 15, 'Administrative Aide I - 01'],
            ['156', 'Joan', 'V.', 'Paran', 11, 'Midwife II - 11'],
            ['157', 'Ceasar Daniel', 'C.', 'Pawell', 20, 'Community Dev\'t Officer III - 18'],
            ['158', 'Doreen', 'D.', 'Pawell', 18, 'Administrative Officer IV - 15'],
            ['159', 'Noel', 'M.', 'Paynohon', 20, 'Tribal Affairs Assistant I - 05'],
            ['160', 'Marilyn', 'M.', 'Pay-ong', 22, 'Administrative Aide I - 01'],
            ['161', 'Jemal', 'ne', 'Pengkiyen', 14, null],
            ['162', 'Roger', 'M.', 'Piagan', 1, 'Administrative Officer IV - 15'],
            ['163', 'Lesing', 'S.', 'Pinmiliw', 33, 'Midwife II - 11'],
            ['164', 'Tomas Jr.', 'L.', 'Pugong', 21, 'Community Affairs Officer I - 11'],
            ['165', 'Telesfora', 'F.', 'Puyongan', 16, 'Nurse II - 16'],
            ['166', 'Genesis De la', 'P.', 'Quiblado', 5, 'Dev\'t Mgmt Officer V - 24'],
            ['167', 'Juliet Constancia', 'B.', 'Quinto', 32, 'Community Dev\'t Officer III - 18'],
            ['168', 'Leomada', 'M.', 'Ragus', 20, 'Midwife II - 11'],
            ['169', 'Sheryl Caesa', 'ea', 'Ramirez', 25, 'Administrative Aide I - 01'],
            ['170', 'Jovita', 'C.', 'Reyes', 15, 'Community Dev\'t Officer III - 18'],
            ['171', 'Norma', 'C.', 'Rimando', 11, 'Nurse II - 16'],
            ['172', 'Gae Loure', 'A.', 'Sabelo', 32, 'Dentist II - 17'],
            ['173', 'Judith', 'M.', 'Salbino', 12, 'Tribal Affairs Assistant I - 05'],
            ['174', 'Bryan', 'G.', 'Sannadan', 7, 'Administrative Aide I - 01'],
            ['175', 'Katherine', 'C.', 'Sapaen', 2, 'Midwife II - 11'],
            ['176', 'Dina', 'B.', 'Sapalit', 29, 'Administrative Aide III - 03'],
            ['177', 'Fermina', 'B.', 'Sarol', 18, 'Administrative Aide I - 01'],
            ['178', 'Jaybee Ann', 'E.', 'Sibal', 3, 'Midwife II - 11'],
            ['179', 'Rowena', 'P.', 'Sicat', 19, 'Community Dev\'t Officer III - 18'],
            ['180', 'Geraldine', 'T.', 'Sigga-ao', 14, 'Administrative Officer IV - 15'],
            ['181', 'Marvin', 'T.', 'Sonay', 33, 'Administrative Aide III - 03'],
            ['182', 'Jona Marie', '.', 'Tabcao', 23, 'Midwife II - 11'],
            ['183', 'Patricia', 'M.', 'Tayaban', 13, 'Midwife II - 11'],
            ['184', 'Reynalda', 'T.', 'Timbreza', 7, 'Community Dev\'t Officer III - 18'],
            ['185', 'Lawrence', 'B.', 'Timpac', 17, 'Tribal Affairs Assistant II - 08'],
            ['186', 'Lemuel', 'B.', 'Timpac', 14, 'Administrative Aide III - 03'],
            ['187', 'Claude  Mia', 'D.', 'Tupeng', 30, 'Attorney IV - 23'],
            ['188', 'Dimonah', 'I.', 'Turas', 5, 'Administrative Aide IV - 04'],
            ['189', 'Amelia', 'V.', 'Tuzon', 5, 'Administrative Officer IV - 15'],
            ['190', 'Michael', 'G.', 'Umaming', 32, 'Dev\'t Mgmt Officer V - 24'],
            ['191', 'Emma', 'G.', 'Venus', 7, 'Midwife II - 11'],
            ['192', 'Hilda', 'D.', 'Verzola', 30, 'Admin. Assistant III - 09'],
            ['193', 'Jacinto', 'A.', 'Verzola', 32, 'Tribal Affairs Assistant II - 08'],
            ['194', 'Lealyn', 'V.', 'Pachong', 29, 'Administrative Assistant III'],
            ['195', 'Chris Jod', 'e', 'Villena', 19, 'Administrative Aide I - 01'],
            ['196', 'Wilson', 'A.', 'Wagawag', 23, 'Tribal Affairs Assistant II - 08'],
            ['197', 'Amber', 'B.', 'Wakit', 10, 'Tribal Affairs Assistant II - 08'],
            ['198', 'Leonica', 'B.', 'Walis', 8, 'Midwife II - 11'],
            ['199', 'Rose', 'A.', 'Wanawan', 29, 'Administrative Officer III - 14'],
            ['200', 'Godofredo', 'D.', 'Maysano', 30, null],
            ['201', 'Francis Marie J30an', 'D.', 'Ibis', 28, null],
            ['202', 'Edgar', 'R.', 'Carag', 22, null],
            ['203', 'Avelina', 'P.', 'Likiyan', 20, null],
            ['204', 'Genalyn', 'S.', 'Badival', 10, null],
            ['205', 'Shirley', '.', 'Ramirez', 25, null],
            ['206', 'Alexan', 'er', 'Tundagui', 18, null],
            ['207', 'Jay-R', 'B.', 'Buminaang', 13, null],
            ['208', 'Rufinda', 'S.', 'Gambican', 16, 'Midwife II - 11'],
            ['209', 'Mac Donnell', 'V.', 'Palangdao', 6, null],
            ['210', 'Paul Mich', 'el', 'Sarol', 19, 'TAA II'],
            ['211', 'Diana Jane', 'C.', 'Natino', 30, 'CAO I'],
            ['212', 'Roland', 'P.', 'Calde', 30, 'Regional Director'],
            ['213', 'Mirtel Jan', 'P.', 'Bayani', 1, 'Engineer II'],
            ['214', 'Percy Jane', 'P.', 'Mukay', 22, 'Engineer II'],
            ['215', 'Jones', 'F.', 'Managtag', 14, 'Punong Barangay'],
            ['216', 'Florentino', 'L.', 'Angnganay', 24, 'AA I'],
            ['217', 'Jane', 'B.', 'Dongla', 14, 'Engineer II'],
            ['220', 'Chester Lee', 'T.', 'Andres', 32, 'AA I'],
            ['221', 'Joy', 'D.', 'Tuangan', 33, 'TAA I'],
            ['222', 'Kevin', 'P.', 'Galusan', 30, 'CMT I'],
            ['223', 'Marietta', 'L.', 'Gamonnac', 17, 'AA I'],
            ['224', 'Lyndon', 'C.', 'Colbongan', 31, null],
            ['225', 'Yenda', 'D.', 'Ayahao', 18, null],
            ['226', 'Pascual Jr.', 'A.', 'Patting', 18, null],
            ['227', 'May Ann', 'T.', 'Cayat', 28, null],
            ['228', 'Jerald', 'P.', 'Camilo', 28, null],
            ['229', 'Jarrid', 'A.', 'Raquedan', 4, 'TAA I'],
        ];

        return array_map(function (array $row) {
            $middle = trim((string) ($row[2] ?? ''));
            $position = trim((string) ($row[5] ?? ''));

            return [
                'ee_sequence_number' => trim((string) $row[0]),
                'first_name' => trim((string) $row[1]),
                'middle_name' => in_array($middle, ['', '.'], true) ? null : $middle,
                'last_name' => trim((string) $row[3]),
                'office_id' => (int) $row[4],
                'position' => $position === '' ? null : $position,
            ];
        }, $rows);
    }
}
